apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: voltdb
  name: voltdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voltdb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: voltdb
    spec:
      containers:
      - image: rokmclsk/test
        name: test
        resources: {}
status: {}
